services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\UploadBundle\Uploader\UploaderInterface:
        class: Kematjaya\UploadBundle\Uploader\FileUploader

    Kematjaya\Upload\Uploader\UploaderInterface:
        alias: Kematjaya\UploadBundle\Uploader\UploaderInterface
        public: true

    Kematjaya\UploadBundle\Manager\DocumentManagerInterface:
        class: Kematjaya\UploadBundle\Manager\DocumentManager

    Kematjaya\UploadBundle\Extension\DocumentExtension: ~

    Kematjaya\UploadBundle\Controller\DownloadController: ~

    Kematjaya\UploadBundle\Type\KmjFileType: ~

    Kematjaya\UploadBundle\Repository\DocumentRepositoryInterface:
        class: Kematjaya\UploadBundle\Repository\DocumentRepository
        tags:
            - doctrine.repository_service

    Kematjaya\UploadBundle\Twig\DownloadExtension: ~
    Kematjaya\UploadBundle\Twig\ImageExtension: ~

    Kematjaya\UploadBundle\EventSubscriber\ImageOptimationSubscriber: ~
