services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\Upload\Uploader\UploaderInterface:
        class: Kematjaya\UploadBundle\Uploader\FileUploader
        public: true
        
    Kematjaya\UploadBundle\Uploader\UploaderInterface:
        class: Kematjaya\UploadBundle\Uploader\FileUploader
            
    Kematjaya\UploadBundle\Manager\DocumentManagerInterface:
        class: Kematjaya\UploadBundle\Manager\DocumentManager

    Kematjaya\UploadBundle\Extension\DocumentExtension:
        class: Kematjaya\UploadBundle\Extension\DocumentExtension
        
    Kematjaya\UploadBundle\Controller\DownloadController:
        class: Kematjaya\UploadBundle\Controller\DownloadController
        
    Kematjaya\UploadBundle\Type\KmjFileType: ~
    Kematjaya\UploadBundle\Repository\DocumentRepositoryInterface:
        class: Kematjaya\UploadBundle\Repository\DocumentRepository
        tags: 
            - doctrine.repository_service
        
    Kematjaya\UploadBundle\Twig\DownloadExtension:
        class: Kematjaya\UploadBundle\Twig\DownloadExtension
        tags: ['twig.extension']